image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: stable-amd64nvidia

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
portal:
  enabled: true
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 5000
  rtmp:
    enabled: true
    ports:
      rtmp:
        protocol: TCP
        enabled: true
        port: 1935
        targetPort: 1935

ingress:
  rtmp:
    autoLink: true

frigate:
  mqtt:
    host: 10.0.0.20
    port: 1883
    authentitcated: false
    #username: frigate
    #password: querty321
  birdseye:
    enabled: true
    mode: motion
  cameras:
    - name: frontdoor
      objects:
        # Optional: list of objects to track from labelmap.txt (default: shown below)
        track:
          - person
      detect:
        height: 720
        width: 1280
      inputs:
        # Required: the path to the stream
        # NOTE: path may include environment variables, which must begin with 'FRIGATE_' and be referenced in {}
        - path: rtsp://testuser:Testpass@10.20.30.50:554
          # Required: list of roles for this stream. valid values are: detect,record,rtmp
          # NOTICE: In addition to assigning the record, and rtmp roles,
          # they must also be enabled in the camera config.
          roles:
            - detect
            - rtmp
      record:
        enabled: False
      # Optional: timeout for highest scoring image before allowing it
      # to be replaced by a newer image. (default: shown below)
      best_image_timeout: 60
      snapshots:
        enabled: True

    - name: patio
      objects:
        track:
          - person
      detect:
        height: 720
        width: 1280
      inputs:
        - path: rtsp://testuser:Testpass@10.20.30.51:554
          roles:
            - detect
            - rtmp
      record:
        enabled: False
      best_image_timeout: 60
      snapshots:
        enabled: True
        
persistence:
  # ADDED config persistence
  config:
    enabled: true
    mountPath: "/mnt/apps/frigate"
  cache:
    enabled: false
    mountPath: "/tmp/cache"
    type: "emptyDir"
  shm:
    enabled: false
    mountPath: "/dev/shm"
    type: "emptyDir"
    medium: "Memory"
  media:
    enabled: true
    mountPath: "/securitymount/frigate"
  coral:
    enabled: true
